2018-07-29 13:47:13,190 ERROR: Exception on /reset_password_request [POST] [in C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\TBW\Documents\footy_site\app\routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\TBW\Documents\footy_site\app\email.py", line 24, in send_password_reset_email
    user=user, token=token),
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\TBW\Anaconda3\envs\footy\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/email/reset_password.txt
2018-07-29 13:50:45,353 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:51]
2018-07-29 15:17:21,652 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:52]
2018-07-29 15:24:48,055 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:52]
2018-07-29 15:27:12,634 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:52]
2018-07-29 15:29:02,112 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:52]
2018-07-29 15:29:42,921 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:52]
2018-07-29 15:35:12,955 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:54]
2018-08-04 00:48:25,343 INFO: Microblog startup [in C:\Users\TBW\Documents\footy_site\app\__init__.py:56]
